### ISSUE TITLE
SignBinary.cmd may no longer be used in this repo.

### ISSUE THREAD

**Issue by curtnichols** [SoundMetrics/build-tools#8]
It appears that .\SignBinary.cmd is no longer used in this repo. Confirm and remove it.

**Comment by fvasquez** [comment]
.\SignBinary.cmd is referenced in the PostBuildEvents of various aris-applications projects including:

ARIScope/Aris.Core/Aris.Core.csproj                                                                                                                
ARIScope/Aris.NAsync/Aris.NAsync.csproj                                                                                                      
ARIScope/Aris.Presentation/Aris.Presentation.csproj                                                                                       
ARIScope/Aris.Utility/Aris.Utility.csproj
ARIScope/ArisFE/Aris.csproj                                       
Aris.ArisFile/Aris.ArisFile.fsproj                                                                                                                          
Aris.Converters/Aris.Converters.fsproj                                                                                                              
Aris.FLib/Aris.FLib.fsproj
Aris.Gps/Aris.Gps.fsproj
Aris.Gps.Svc/Aris.Gps.Svc.fsproj
Aris.Gps.Svc.Cfg/Aris.Gps.Svc.Cfg.fsproj   
Aris.HID/Aris.HID.fsproj
Aris.HID.UX/Aris.HID.UX.csproj              
Aris.Messages/Aris.ProtocolMessages.csproj
Aris.Model/Aris.Model.fsproj
Aris.Model.Native/Aris.Model.Native.vcxproj                                                                                                   
Aris.Presentation.Controls/Aris.Presentation.Controls.csproj                                                                           
Aris.Presentation.WPF/Aris.Presentation.WPF.fsproj                                                                                        
Aris.Shader/Aris.Shader.csproj
Aris.Shell/Aris.Shell.vcxproj
Aris.SonarView.Lib/Aris.SonarView.Lib.fsproj                                                                                                    
Aris.SonarViewCtl/Aris.SonarViewCtl.csproj
Aris.Update/Aris.Update/Aris.Update.fsproj
Aris.Update/Aris.Update.App/Aris.Update.App.csproj                                                                                     
Aris.Update/Aris.Update.CM/Aris.Update.CM.fsproj                                                                                        
Aris.Util/Aris.Util.fsproj
ArisCmdr/ArisCmdr/ArisCmdr.csproj
ArisCmdr/ArisCmdr.Core/ArisCmdr.Core.fsproj
ArisCmdr/ArisCmdr.VM/ArisCmdr.VM.fsproj                                                                                                    
SmcFw/SmcFw.vcxproj
ViewTrace/ViewTrace.fsproj                                                                                                       

The SignBinary.cmd referenced in these project files is submodules/build-tools/SignBinary.cmd.
A Tools/sign-binary.cmd also exists in the aris-applications repo but I don't see it referenced anywhere.

The sign-binary.cmd in the aris-applications repo uses digicert to sign.

```
"%SIGNTOOL_DIR%\signtool" sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a %TARGET_PATH%
```

The SignBinary.cmd in this build-tools repo uses verisign to sign.

"%SIGNTOOL_DIR%\signtool" sign /debug /a /t http://timestamp.verisign.com/scripts/timstamp.dll %TARGET_PATH%

**Comment by fvasquez** [comment]
The aris-diagnostics repo uses submodules/build-tools/SignBinary.cmd to sign binaries and I suspect other SoundMetrics repos do as well.  Because of that I will port the changes made to tool/sign-binary.cmd in aris-applications to submodules/build-tools/SignBinary.cmd in this build-tools repo.

**Comment by fvasquez** [comment]
We will need to update this submodule in all the repos that reference it for the signatory change to take effect.
